namespace MurakamiRyujirou.Cube
{
    /// ƒpƒlƒ‹ˆÊ’u.
    public enum PanelPositions
    {
        UBL = 0,
        UBR = 1,
        UFR = 2,
        UFL = 3,
        FLU = 4,
        FRU = 5,
        FDR = 6,
        FDL = 7,
        RFU = 8,
        RBU = 9,
        RBD = 10,
        RDF = 11,
        BLU = 12,
        BDL = 13,
        BDR = 14,
        BRU = 15,
        LBU = 16,
        LFU = 17,
        LDF = 18,
        LBD = 19,
        DFL = 20,
        DFR = 21,
        DBR = 22,
        DBL = 23,
        UB = 24,
        UR = 25,
        UF = 26,
        UL = 27,
        FU = 28,
        FR = 29,
        FD = 30,
        FL = 31,
        RU = 32,
        RB = 33,
        RD = 34,
        RF = 35,
        BU = 36,
        BL = 37,
        BD = 38,
        BR = 39,
        LU = 40,
        LF = 41,
        LD = 42,
        LB = 43,
        DF = 44,
        DR = 45,
        DB = 46,
        DL = 47,
        U = 48,
        F = 49,
        R = 50,
        B = 51,
        L = 52,
        D = 53
    }
}